
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np
array=np.arange(10)  #0 to 9 (last exclude hai )
array=np.arange(2,11)
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [4]:
#reshape 3by 3 karna 
array=np.arange(1,10)
#array

reshapearray=array.reshape((3,3))
reshapearray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [8]:
reshape_element=reshapearray[1][1]
reshape_element

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [11]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array1+array2
array1-array2
array1*array2
array1/array2

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [17]:
array=np.array([1,2,3])
array_sum=array.sum()
array_mean=array.mean()
array_std=array.std()
print(array_sum,array,array_mean,array_std)

6 [1 2 3] 2.0 0.816496580927726


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [27]:
random_array=np.random.randint(1,100,size =(5,5)) #ranint size ke lyae funct hai 
random_array

array([[17, 45, 62,  5, 48],
       [ 5, 84,  1, 66,  6],
       [41, 76, 38, 69, 58],
       [87, 79, 28, 42,  5],
       [ 9,  1,  4, 30, 94]])

Replace all values in the sub-array with a specific value.


In [28]:
#sub array means specific row and colmn kou change karana 
random_array[1:4,:] =10 #last khali islyaee hai sab colm ayengay baki dou mae row ki sli9cing ki hai 
random_array

array([[17, 45, 62,  5, 48],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [ 9,  1,  4, 30, 94]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [36]:
arr=np.array( [[1, 2], [3, 4], [5, 6], [7, 8]])
arr

arr[[1,3],:]  #last wala colm rep kar raha hai 

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [43]:
array=np.array([0,1,2])
array

#tile  func value repeat karta hai 
new_array=np.tile(array,(3,1))  # 3 bar row kou repeat karaega or agay secon mae colm kou repeat karaega (tile ke fun mae dou value ati hai first row kitni bar and colm kitni bar)
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [46]:
array_1d=np.array([0,1,2])
new_array+array_1d

array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [53]:
random_arr1=np.random.randint(1,100,size=(3,3))
random_arr1





array([[25, 47, 37],
       [53, 64, 74],
       [32, 20, 20]])

In [54]:
random_arr2=np.random.randint(1,100,size=(3,3))
random_arr2

array([[63, 24, 12],
       [70, 81, 69],
       [27, 35, 73]])

In [55]:
#hstack and vstack   horizontal and vertical
concatenated_horizontally=np.hstack((random_arr1+random_arr2))
concatenated_horizontally


array([ 88,  71,  49, 123, 145, 143,  59,  55,  93])

In [57]:
concatenated_vertically=np.vstack((random_arr1+random_arr2))
concatenated_vertically

array([[ 88,  71,  49],
       [123, 145, 143],
       [ 59,  55,  93]])

In [61]:
#hsplit and vsplit
splitted_array=np.hsplit(concatenated_horizontally,3)
splitted_array

[array([88, 71, 49]), array([123, 145, 143]), array([59, 55, 93])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [65]:
# Define the array
array = np.array([1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5,2,2,2])


counts = np.bincount(array)
mode = np.argmax(counts)
print(f"The mode of the array is: {mode}")

The mode of the array is: 2


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

